### ISSUE TITLE
Cannot find module balanced-match

### ISSUE THREAD

**Issue by jrock2004** [danlynn/ember-cli-docker-template#3]
Trying to pull the latest and I get the following error:

```
Attaching to aaaapplist_server_1
[36mserver_1 | [0mCannot find module 'balanced-match'
[36mserver_1 | [0mError: Cannot find module 'balanced-match'
[36mserver_1 | [0m    at Function.Module._resolveFilename (module.js:337:15)
[36mserver_1 | [0m    at Function.Module._load (module.js:287:25)
[36mserver_1 | [0m    at Module.require (module.js:366:17)
[36mserver_1 | [0m    at require (module.js:385:17)
[36mserver_1 | [0m    at Object.<anonymous> (/myapp/node_modules/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/node_modules/broccoli-kitchen-sink-helpers/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/index.js:2:16)
[36mserver_1 | [0m    at Module._compile (module.js:435:26)
[36mserver_1 | [0m    at Object.Module._extensions..js (module.js:442:10)
[36mserver_1 | [0m    at Module.load (module.js:356:32)
[36mserver_1 | [0m    at Function.Module._load (module.js:311:12)
[36mserver_1 | [0m    at Module.require (module.js:366:17)
[36maaaapplist_server_1 exited with code 1
[0m
```

**Comment by danlynn** [comment]
Just wondering if you resolved this issue.

I wondering if this is a known bug with this specific ember.js version.

Also, I haven't tested ember-cli-docker-template with the latest ember-cli docker image.  I've completely replaced this project with a new docker-dev tool that I'll be publishing to github soon.

**Comment by jrock2004** [comment]
Well, I just removed everything, pulled all again and now it works
